config/routes.rb
Blogosphere::Application.routes.draw do
  devise_for :users

  # Static pages
  get "editors/index"
  get "about/index"

  # Resources

  # Cart is only used as a controller to add/delete/view to the cart
  resources :cart, :only => [:index, :create, :destroy] 

  # Magazines is the controller that shows all the magazines in a list.
  get "magazines/purchased", :as => 'purchased_magazines'
  resources :magazines, :only => [:index, :show]

  # Checkout is the controller that makes the payment and saves the payment information to the DB
  resources :checkout, :as => :checkouts, :only => [:new, :create]

  root :to => 'home#index'

  namespace :administration do
    resources :checkouts, :only => [:index, :show, :update]
  end
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base

	attr_accessor :is_by_post
  attr_accessible :post_code, :city, :address_line_1, :address_line_2, :county, :country
  belongs_to :user

  has_many :checkout_magazines
  has_many :magazines, :through => :checkout_magazines

  validates :address_line_1, :presence => true, :unless => :magazines_all_ebooks
  validates :post_code, :presence => true, :unless => :magazines_all_ebooks
  validates :city, :presence => true, :unless => :magazines_all_ebooks

	private
	def magazines_all_ebooks
		!@is_by_post
	end

end

app/controllers/administration/checkouts_controller.rb
class Administration::CheckoutsController < ApplicationController
http_basic_authenticate_with :name => ENV['AUTH_USERNAME'], :password => ENV['AUTH_PASSWORD']
   
    def index
           # Get a list of all the checkouts that have not been sent
        checkouts = Checkout.all
        @unsent_checkouts = checkouts.select do |checkout|
            checkout.magazines.any? do |magazine|
            magazine.purchase_type == 'print'
            end
        end
    end

    def show 
        @checkout = Checkout.find(params[:id])
        # @user = User.where(:id => @checkout[0].user_id)
        #select all the print magazines in the purchase
        @checkout_print_magazines = @checkout.magazines.select do |magazine|
            magazine.purchase_type =="print"
        end

        #get the checkout_magazine and select the print ones, we dont want the e-magazines in this admin panel
        
        #get the checkout and list the transaction_id and email and the shipping address
        #Iterate through each magazine in the checkout and list the magazine issue number and whether it is sent or not, this can have the bootstrap button class
    end

    def update
        checkout = Checkout.find(params[:id])
        checkout.sent = true
        checkout.save

        flash[:notice] = "You have successfully updated checkout #{checkout.id}"
        redirect_to administration_checkouts_path
        #this is going to be update, when the link is clicked then I can have a Javascript popup saying are you sure all the items in this checkout have been posted
    #Then is can update the checkouts status to sent: true and redirect_back to the checkout that it was on
    end

    
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
	before_filter :authenticate_user!

	def get_purchase_information
		@to_purchase_magazines = get_cart_magazines
		@total_price_magazines = get_cart_price

		@has_at_least_a_post = @to_purchase_magazines.any? do |magazine|
			magazine.purchase_type == 'print'
		end
		@packaging_price = @has_at_least_a_post ? 2 : 0

		@subtotal = @total_price_magazines + @packaging_price
	end

	def new
		get_purchase_information
		@checkout = Checkout.new
	end

	def create
		get_purchase_information
		@checkout = Checkout.new(params[:checkout])
		binding.pry
		@checkout.is_by_post = @has_at_least_a_post
		unless @checkout.valid?
			return render 'new'
		end

		# Create a Customer
		customer = Stripe::Customer.create(
			:card => params[:stripeToken],
			:description => current_user.email
		)

		# Charge the Customer instead of the card
		charge = Stripe::Charge.create(
			:amount => @subtotal + 100,
			:currency => "gbp",
			:customer => customer.id
		)
		unless charge.paid
			flash[:alert] = "There has been a problem processing your request"
			return render root_path
		end

		@checkout.user = current_user
		@checkout.stripe_transaction_id = charge.id
		@checkout.total_price = @subtotal
		@checkout.sent = false
		@checkout.save

		@to_purchase_magazines.each do |magazine|
			@checkout.magazines.push(magazine)
			@checkout.save

		end
		initialize_new_cart
		binding.pry

		has_at_least_a_e_magazine = @to_purchase_magazines.any? do |magazine|
										 	magazine.purchase_type == 'e-book'
										end
		binding.pry
		mandrill_mailer(has_at_least_a_e_magazine, @checkout.stripe_transaction_id)
	end

	private
	def mandrill_mailer(checkout_type, transaction_id)
		binding.pry
		@checkout_transaction_id = transaction_id
		@checkout_type = checkout_type
		user_email = current_user.email
		UserMailer.welcome_email(user_email, @checkout_type, @checkout_transaction_id).deliver
		render :template => 'checkout/create'
	end
end

app/views/checkout/create.html.erb
<%=render 'layouts/header'%>

<div class="span 10 offset1 confirmation_page">
	<h2>Thanks, your payment was successful, you will be sent an email with your confirmation code</h2> 

	<% if @checkout_type == true %>
		<h2>Follow this link www.google.com to access the e_magazine</h2>
	<%end%>
</div>

app/views/checkout/new.html.erb
<%=render 'layouts/header'%>
<div class="checkout_view clearfix fluid-row">

  <div class="span4 offset1 shipping_address">
    <% if @checkout.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@checkout.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @checkout.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for @checkout do |f| %>
      <% if @has_at_least_a_post %>
        <h3>ENTER SHIPPING ADDRESS HERE</h3>
        <p><%= f.text_field :address_line_1, placeholder: 'Address Line 1', :required => true %></p>
        <p><%= f.text_field :address_line_2, placeholder: 'Address Line 2'%></p>
        <p><%= f.text_field :city, placeholder: 'Enter your city here', :required => true %></p>
        <p><%= f.text_field :post_code, placeholder: 'Enter your postcode here', :required => true %></p>
        <p class="drop_down_country"><%= f.select :country, options_for_select(["United Kingdom"])%></p>
      <% end %>
  	  <script
  	    src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
        data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
        data-amount="<%= @subtotal%>"
  	    data-name="Blogosphere"
  	    data-description="Amount Payable: £<%= @subtotal%>"
  	    data-image="<%= image_path('128x128.png')%>">
      </script>
    <% end %>
  </div>

  <div class="span3 cards_accepted">
    <h3>CARDS ACCEPTED</h3>
    <ul>
      <li class="payment_cards"><%=image_tag('visa.jpg', :width => '20px', :class => "payment_images")%></li>
      <li class="payment_cards"><%=image_tag('mastercard.jpg', :width => '20px', :class => "payment_images")%></li>
      <li class="payment_cards"><%=image_tag('american-express.jpg', :width => '20px', :class => "payment_images")%></li>
    </ul>
  </div>

  <div class="span3 checkout_basket_items">
    <h3>CHECKOUT BASKET</h3>
    <h6>PRODUCTS: £<%= @total_price_magazines %></h6>
    <h6>POST AND PACKAGING: £<%= @packaging_price %></h6>
    <h6>TOTAL: £<%= @subtotal %></h6>

    <%= button_to 'Go back to Magazine list', magazines_path, :id => 'checkout_button', :method => :get  %>
  </div>

</div>
<!-- I need to edit this form so that I can pass the magazine ids and subtotal to the create controller so that I can create a checkout -->


<%=render 'layouts/footer'%>