config/routes.rb
Blogosphere::Application.routes.draw do
  devise_for :users

  # Static pages
  get "editors/index"
  get "about/index"

  # Resources

  # Cart is only used as a controller to add/delete/view to the cart
  resources :cart, :only => [:index, :create, :destroy] 

  # Magazines is the controller that shows all the magazines in a list.
  get "magazines/purchased", :as => 'purchased_magazines'
  resources :magazines, :only => [:index, :show]

  # Checkout is the controller that makes the payment and saves the payment information to the DB
  resources :checkout, :as => :checkouts, :only => [:new, :create]

  root :to => 'home#index'

  namespace :administration do
    resources :checkouts, :only => [:index, :show, :update]
  end
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  attr_accessible :image_url, :issue_number, :month, :name, :price, :purchase_type, :path

  has_many :checkout_magazines
  has_many :checkouts, :through => :checkout_magazines
  
  def get_secure_url
     # Get the S3 object
     s3 = AWS::S3.new(
       :access_key_id => ENV["AWS_KEY_ID"],
       :secret_access_key => ENV["AWS_SECRET_KEY"]
     )
     
     # Get the S3 bucket
     bucket = s3.buckets[Blogosphere::Application.config.s3[:bucket_name]]
     
     # get the magazine file name
     magazine_object = bucket.objects[self.path]
     
     # create a secure url for self.path inside the bucket
     
     expiry_in_minutes = Blogosphere::Application.config.s3[:expiry_in_minutes]
     magazine_object.url_for(:get, {
         :expires => expiry_in_minutes.minutes.from_now,
         :secure => true
     }).to_s
  end
  
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  def index

    # There is an inconsistency with your template and your action here.
    # looks like magazine is not being set, this renders an empty download/index page.

    @magazine = Magazine.all
  end

  def purchased
    #why does this not work!!
    #check each checkout to see if magazine contains an e-book
    checkout_with_e_book = current_user.checkouts.select do |checkout|
      checkout.magazines.any? do |magazine|
      magazine.purchase_type == 'e-book'
      end
    end

    @purchased_e_magazine = []
    #This method can be improved - it is iterating through each checkout and each magazine and pushing it into an array if it is an e-magazine
    e_magazines = checkout_with_e_book.each do |checkout|
      checkout.magazines.each do |magazine|
        if magazine.purchase_type =="e-book"
           @purchased_e_magazine << magazine
        end
      end
    end
  end

  def show

  end

end

app/views/magazines/index.html.erb
<%=render 'layouts/header'%>

<div class="fluid-row clearfix magazine_index_container">
	<div class="span3 offset1" id="checkout">
		<h3>CART</h3>
		<div id="basket" data-magazinename="" data-magazinecost="">
		</div>
		<!-- SUBTOTAL: -->
		<div class="subtotal" data-subtotal="0">
		</div>
		<div class="payment_checkout">
      <%= button_to "Proceed to Checkout", new_checkout_path, :id => 'checkout_button', :method => :get %>
		</div>
	</div>
  
  <% @magazine.each do |x| %>
	<div class="span4 magazine_data" data-id="<%=x.id%>"data-price="<%=x.price%>" data-name="<%=x.name%>">
	    <%=image_tag x.image_url, :width => 200 %><br>
	    <div id="mag_name"><%= x.name %> (<%= x.purchase_type%>)</div><br>
	    <div id="mag_price">£<%= x.price %></div>
	    <button class="add_to_basket">ADD TO CART</button>
	</div>
	<%end%>
</div>

<script type="text/template" id="cart-template">
  <div class="wrapper" data-cost="{{=price}}" data-magazine-id="{{=id}}">
      <h6 class="magazine_checkout">{{=name}} ({{=purchase_type}})</h6>
			<img class="trash_icon" title="click here to remove from cart" src="http://b.dryicons.com/images/icon_sets/symbolize_icons_set/png/128x128/trash.png" />
  </div>
</script>

<%=render 'layouts/footer'%>

app/views/magazines/purchased.html.erb
<%=render 'layouts/header'%>

<div class="fluid-row clearfix magazine_index_container">
  <% @purchased_e_magazine.each do |magazine| %>
  <div class="span10 offset1 clearfix">
    <div class="span5">
      <h3><%=magazine.name%>, Issue number: <%=magazine.issue_number%></h3>
    </div>
    <div class="span4">
      <button><a href="#">CLICK HERE TO ACCESS MAGAZINE</a></button>
      <!-- This will be a link to the show action, here I will call the magazine model get_url method and it will build the url for amazon -->
    </div>
  </div>
  <%end%>
</div>

<%=render 'layouts/footer'%>