config/routes.rb
Blogosphere::Application.routes.draw do
  devise_for :users

  # Static pages
  get "editors/index"
  get "about/index"

  # Resources

  # Cart is only used as a controller to add/delete/view to the cart
  resources :cart, :only => [:index, :create, :destroy] 

  # Magazines is the controller that shows all the magazines in a list.
  get "magazines/purchased", :as => 'purchased_magazines'
  resources :magazines, :only => [:index, :show]

  # Checkout is the controller that makes the payment and saves the payment information to the DB
  resources :checkout, :as => :checkouts, :only => [:new, :create]

  root :to => 'home#index'

  namespace :administration do
    resources :checkouts, :only => [:index, :show, :update]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer row-fluid">
	<div id="footerwrapper" class="span10 offset1">
		<ul>
			<li><a href="#">terms of website use</a></li>
			<li><a href="#">terms and conditions</a></li>
			<li><a href="#">privacy</a></li>
			<li><a href="#">contact us</a></li>
		</ul>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header id="mainheader">
    
  <div class="navbar clearfix" id="top-nav">
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
   
        <!-- Be sure to leave the brand out there if you want it shown -->
   
        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse top_nav clearfix">
          <ul class="clearfix top_header">
                <% if user_signed_in? %>
                  <a class="brand" href="">welcome <%=current_user.email%></a>
		  <%= link_to 'Purchased Magazines', purchased_magazines_path %>
                  <%= link_to 'SIGN OUT', destroy_user_session_path, :method => :delete, :class => 'brand' %>
                  <!-- <a class="brand" href="/users/sign_out">SIGN OUT</a> -->
                <% else %>
                <%# if user_signed_in !== true %>
                   <a class="notice brand"><%= notice %></a>
                  <!--  <a class="alert brand"><%#= alert %></a> --> 
                  <a class="brand login first" href="/users/sign_up">SIGN UP</a>
                  <a class="brand login" href="/users/sign_in">SIGN IN</a>
                <% end %>

                <a class="facebook" href="https://www.facebook.com/pages/Blogosphere-Magazine/345634805572414?ref=ts&fref=ts">
                  Facebook
                </a>

                <a class="twitter" href="https://twitter.com/BlogosphereM">
                  Twitter
                </a>

            </ul>
          <!-- .nav, .navbar-search, .navbar-form, etc -->
        </div>
   <!--  </div> -->
  </div>

  <div class="row-fluid">
    <div id="logo" class="span10 offset1">
      <h1>BLOGOSPHERE MAGAZINE</h1>
      <h6>'for bloggers. about bloggers'</h6>
      <div style="clear:both;"></div>
    </div>
  </div>

  <div class="row-fluid" id="middlenav">
      <ul>
        <li><a href="/">home</a></li>
        <li><a href="/about/index">about us</a></li>
        <li><a href="/editors/index">editors</a></li>
        <li><a href="/magazines">buy</a></li>
      </ul>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogosphere</title>
  <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
  <!-- improves the html5 support in older versions of Internet Explorer -->
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="description" content="Blogosphere">
  <meta name="keywords" content="Blogging, socialmedia, magazine">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogosphere</title>
  <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://decoded.co/css/din-family.css" type="text/css"/>
  <link rel="stylesheet" href="/app/assets/stylesheets/din_typography.css" type="text/css"/>
  <link rel="stylesheet" href="/app/assets/stylesheets/typography.css" type="text/css"/>
  <!-- improves the html5 support in older versions of Internet Explorer -->
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= yield %>
</body>
</html>